import {createListen} from './listen.js';
import {createComposer} from './composer.js';
import {audio,names,shortcuts,pitch,play,ready,stop,stopAll,volume} from './audio.js';
const $=s=>document.querySelector(s);
audio.selected='alto';let viewer,noteTimeout,errorTimeout,showNotes=false;
function showError(message){$('#audio-status').textContent=message;clearTimeout(errorTimeout);errorTimeout=setTimeout(()=>$('#audio-status').textContent='',6500);}
function modelNote(n){const pitch=((n%12)+12)%12,white=[0,2,4,5,7,9,11];return white.reduce((best,key)=>Math.min((key-pitch+12)%12,(pitch-key+12)%12)<Math.min((best-pitch+12)%12,(pitch-best+12)%12)?key:best,white[0]);}
function updateActive(){document.querySelectorAll('[data-note]').forEach(b=>{const target=Number(b.dataset.note),active=[...audio.active.entries()].some(([id,a])=>a.n===target||id.startsWith('song-')&&modelNote(a.n)===target);b.classList.toggle('active',active);b.setAttribute('aria-pressed',active);});viewer?.setActive([...audio.active.entries()].map(([id,a])=>id.startsWith('song-')?modelNote(a.n):a.n));}
audio.onchange=n=>{updateActive();if(n!==undefined){const p=pitch(n);$('#note-label').textContent=p.written;$('#note-concert').textContent=`Concert ${p.concert}`;$('#note-indicator').classList.add('visible');}clearTimeout(noteTimeout);if(!audio.active.size)noteTimeout=setTimeout(()=>$('#note-indicator').classList.remove('visible'),1200);};audio.onerror=showError;
const listen=createListen();
const composer=createComposer({closeListen:listen.close});
function stopDemo(){listen.stop();composer.stop();stopAll();}
function toggleKeyboard(open){$('#keyboard-panel').hidden=!open;$('#keyboard-toggle').setAttribute('aria-expanded',open);$('#keyboard-toggle').setAttribute('aria-label',open?'Close piano keyboard':'Open piano keyboard');$('#keyboard-toggle').title=open?'Close keyboard':'Open keyboard';if(!open){stopDemo();$('#keyboard-toggle').focus({preventScroll:true});}}
$('#keyboard-toggle').addEventListener('click',()=>toggleKeyboard($('#keyboard-panel').hidden));$('#close-keyboard').addEventListener('click',()=>toggleKeyboard(false));$('#fallback-keyboard').addEventListener('click',()=>toggleKeyboard(true));
$('#listen-toggle').addEventListener('click',()=>{if(!$('#listen-panel').hidden&&!$('#keyboard-panel').hidden){toggleKeyboard(false);$('#close-listen').focus({preventScroll:true});}});
$('#listen-toggle').addEventListener('click',()=>composer.close());
function stopRotation(){viewer?.setRotate(false);$('#rotate-toggle').setAttribute('aria-pressed','false');}
$('#reset-view').addEventListener('click',()=>{stopRotation();viewer?.reset();});
function bindNote(b,n){b.dataset.note=n;b.setAttribute('aria-pressed','false');b.addEventListener('pointerdown',e=>{e.preventDefault();stopDemo();b.focus({preventScroll:true});b.setPointerCapture(e.pointerId);play(n,`pointer-${e.pointerId}`);});for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,e=>stop(`pointer-${e.pointerId}`));b.addEventListener('click',e=>{if(e.detail===0){stopDemo();play(n,`accessible-${n}`,{tap:true});}});}
function buildKeyboard(){let whites=0;$('#keyboard').replaceChildren();for(let n=0;n<13;n++){const black=[1,3,6,8,10].includes(n),b=document.createElement('button');b.className='piano-key'+(black?' black':'');b.setAttribute('aria-label',`Play ${names[n%12]}${audio.octave+Math.floor(n/12)} (${shortcuts[n].toUpperCase()})`);b.innerHTML=`<span>${names[n%12]}</span><small>${shortcuts[n].toUpperCase()}</small>`;if(black)b.style.left=`calc(${whites*12.5}% - 3.5%)`;else whites++;bindNote(b,n);$('#keyboard').append(b);}$('#octave-label').textContent=`Octave ${audio.octave}`;$('#octave-down').disabled=audio.octave===4;$('#octave-up').disabled=audio.octave===5;}
for(const [id,amount] of [['#octave-down',-1],['#octave-up',1]])$(id).addEventListener('click',()=>{stopDemo();audio.octave=Math.max(4,Math.min(5,audio.octave+amount));buildKeyboard();updateLabels();});$('#volume').addEventListener('input',e=>volume(Number(e.target.value)/100));
function updateLabels(){if(!viewer||!showNotes)return;const container=$('#note-labels'),rect=$('#stage').getBoundingClientRect();for(const p of viewer.keyPositions()){let b=container.querySelector(`[data-note="${p.note}"]`);if(!b){b=document.createElement('button');b.className='model-note';bindNote(b,p.note);container.append(b);}b.textContent=pitch(p.note).written;b.setAttribute('aria-label',`Play ${pitch(p.note).written} on the alto`);const left=[9,4,0].includes(p.note),dy=p.note===11?-10:p.note===7?9:0;b.classList.toggle('label-left',left);b.style.left=`${p.x-rect.left+(left?-65:48)}px`;b.style.top=`${p.y-rect.top+dy}px`;b.hidden=!p.visible||p.y<rect.top+20||p.y>rect.bottom-100;}}
$('#notes-toggle').addEventListener('click',()=>{showNotes=!showNotes;document.body.classList.toggle('notes-visible',showNotes);$('#notes-toggle').setAttribute('aria-pressed',showNotes);$('#note-labels').hidden=!showNotes;updateLabels();});
$('#rotate-toggle').addEventListener('click',()=>{const enabled=$('#rotate-toggle').getAttribute('aria-pressed')!=='true';viewer?.setRotate(enabled);$('#rotate-toggle').setAttribute('aria-pressed',enabled);});
document.addEventListener('keydown',e=>{if(e.key==='Escape'){stopDemo();stopRotation();if(!$('#keyboard-panel').hidden)toggleKeyboard(false);return;}if($('#keyboard-panel').hidden||e.ctrlKey||e.metaKey||e.altKey||e.target.matches('input,textarea,select'))return;const n=shortcuts.indexOf(e.key.toLowerCase());if(n!==-1){e.preventDefault();if(!e.repeat){stopDemo();play(n,`key-${n}`);}}});document.addEventListener('keyup',e=>{const n=shortcuts.indexOf(e.key.toLowerCase());if(n!==-1)stop(`key-${n}`);});
window.addEventListener('blur',()=>{stopDemo();stopRotation();});document.addEventListener('visibilitychange',()=>{if(document.hidden){stopDemo();stopRotation();}});
function viewerError(){$('#loading').hidden=true;$('#viewer-error').hidden=false;$('#reset-view').disabled=true;$('#notes-toggle').disabled=true;$('#rotate-toggle').disabled=true;}
buildKeyboard();
try{const {createViewer}=await import('./viewer.js');viewer=await createViewer($('#viewport'),{onPlay:n=>{stopDemo();play(n,`model-${n}`,{tap:true});},onUnlock:()=>ready().catch(e=>showError(e.message)),onInteract:stopRotation,onView:updateLabels,onProgress:percent=>{$('#loading').firstChild.textContent=percent?`Loading the alto · ${percent}%`:'Preparing your instrument';},onHover(n,e){const tip=$('#key-tooltip');tip.hidden=n===null||showNotes;if(n!==null&&e){tip.textContent=`Play ${pitch(n).written}`;const r=$('#stage').getBoundingClientRect();tip.style.left=Math.min(e.clientX-r.left,r.width-100)+'px';tip.style.top=e.clientY-r.top+'px';}},onError:viewerError});$('#loading').hidden=true;const url=new URL(location.href);url.searchParams.delete('instrument');history.replaceState(null,'',url);}catch(e){console.error(e);viewerError();}
window.saxophone={get scene(){return viewer?.state;},get activeNotes(){return [...audio.active.values()].map(a=>a.n);},get audioState(){return audio.context?.state;},get keyPositions(){return viewer?.keyPositions()||[];}};
