import {instruments} from './instruments.js';
export const names=['C','C♯','D','E♭','E','F','F♯','G','A♭','A','B♭','B'];
export const shortcuts=['a','w','s','e','d','f','t','g','y','h','u','j','k'];
export const audio={selected:'alto',octave:4,volume:.65,active:new Map(),context:null,master:null,onchange:()=>{},onerror:()=>{}};
const buffers=new Map();
export const midiName=m=>names[((m%12)+12)%12]+(Math.floor(m/12)-1);
export function pitch(n){const written=(audio.octave+1)*12+n;return {written:midiName(written),concert:midiName(written+instruments[audio.selected].offset)};}
export async function ready(){if(!audio.context){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw Error('Audio is unavailable in this browser.');audio.context=new Audio();audio.master=audio.context.createGain();audio.master.gain.value=audio.volume*.7;audio.master.connect(audio.context.destination);}if(audio.context.state!=='running')await audio.context.resume();}
async function sample(voice,base){const key=`${voice}-${base}`;if(!buffers.has(key))buffers.set(key,fetch(`assets/audio/${voice}-C${base/12-1}.mp3`).then(r=>{if(!r.ok)throw Error('Sound couldn’t load. Try another key.');return r.arrayBuffer();}).then(a=>audio.context.decodeAudioData(a)).catch(e=>{buffers.delete(key);throw e;}));return buffers.get(key);}
export async function play(n,id,{tap=false}={}){if(audio.active.has(id))return;const item={n},s=instruments[audio.selected],midi=(audio.octave+1)*12+n+s.offset;audio.active.set(id,item);audio.onchange(n);try{await ready();const base=Math.max(36,Math.min(72,Math.round(midi/12)*12)),buffer=await sample(s.voice,base);if(audio.active.get(id)!==item)return;const source=audio.context.createBufferSource(),gain=audio.context.createGain(),now=audio.context.currentTime;source.buffer=buffer;source.playbackRate.value=2**((midi-base)/12);source.connect(gain);gain.connect(audio.master);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.7,now+.025);Object.assign(item,{source,gain});source.onended=()=>{source.disconnect();gain.disconnect();if(audio.active.get(id)===item){audio.active.delete(id);audio.onchange();}};source.start();if(tap)item.timer=setTimeout(()=>stop(id),650);}catch(e){if(audio.active.get(id)===item){audio.active.delete(id);audio.onchange();audio.onerror(e.message||'Sound couldn’t load. Please try again.');}}}
export function stop(id){const item=audio.active.get(id);if(!item)return;clearTimeout(item.timer);audio.active.delete(id);if(item.source){const now=audio.context.currentTime;item.gain.gain.cancelScheduledValues(now);item.gain.gain.setTargetAtTime(0,now,.045);item.source.stop(now+.22);}audio.onchange();}
export function stopAll(){for(const id of [...audio.active.keys()])stop(id);}
export function volume(v){audio.volume=v;if(audio.master)audio.master.gain.setTargetAtTime(v*.7,audio.context.currentTime,.02);}
