import {audio,play,ready,stop,stopAll} from './audio.js';

const LETTERS=['E','F','G','A','B','C','D'];
const NATURAL=[64,65,67,69,71,72,74];
const DURATIONS=[['Whole',4],['Half',2],['Quarter',1],['Eighth',.5],['16th',.25]];
const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));

export function createComposer({closeListen=()=>{}}={}){
 const $=s=>document.querySelector(s),button=$('#compose-toggle');
 const panel=document.createElement('section');panel.id='compose-panel';panel.hidden=true;panel.setAttribute('aria-labelledby','compose-title');
 panel.innerHTML=`<div class="panel-heading"><div><span class="compose-eyebrow">YOUR ALTO, YOUR MELODY</span><h2 id="compose-title">Create a song</h2></div><button id="close-compose" class="icon-button" aria-label="Close composer">×</button></div><label class="compose-title-label">Title<input id="compose-name" maxlength="40" value="Untitled melody" aria-label="Song title"></label><p class="compose-help">Choose a note length, then click the staff to place it. Click a note to remove it.</p><div class="compose-toolbar"><div id="compose-durations" class="compose-options" role="group" aria-label="Note length"></div><div id="compose-accidentals" class="compose-options" role="group" aria-label="Accidental"><button data-acc="0" aria-pressed="true">♮</button><button data-acc="1" aria-pressed="false">♯</button><button data-acc="-1" aria-pressed="false">♭</button></div><button id="compose-rest" class="compose-rest" aria-pressed="false">＋ Rest</button></div><div class="staff-scroll"><svg id="compose-staff" role="img" aria-label="Clickable treble staff for composing a melody"></svg></div><div class="compose-transport"><button id="compose-play" class="compose-primary">Play</button><button id="compose-stop" disabled>Stop</button><button id="compose-undo" disabled>Undo</button><button id="compose-clear" disabled>Clear</button><label>Tempo <input id="compose-tempo" type="range" min="60" max="180" value="112"><output id="compose-bpm">112 BPM</output></label></div><p id="compose-status" role="status" aria-live="polite">Click anywhere on the staff to add your first note.</p>`;
 document.body.append(panel);button.setAttribute('aria-controls',panel.id);button.setAttribute('aria-expanded','false');button.removeAttribute('aria-pressed');
 let notes=[],beats=1,accidental=0,rest=false,playing=false,frame=0,token=0,started=new Set(),sounding=new Map(),began=0,bpm=112;
 const staff=$('#compose-staff');
 function totalBeats(){return Math.max(4,notes.reduce((end,n)=>Math.max(end,n.at+n.beats),0)+1);}
 function render(){const width=88+totalBeats()*64;staff.setAttribute('viewBox',`0 0 ${width} 150`);staff.setAttribute('width',width);staff.setAttribute('height',150);let svg='';for(let i=0;i<5;i++){const y=44+i*12;svg+=`<line class="staff-line" x1="52" y1="${y}" x2="${width-12}" y2="${y}"/>`;}svg+='<text class="clef" x="14" y="103">𝄞</text>';for(let b=0;b<=totalBeats();b+=4){const x=72+b*64;svg+=`<line class="bar-line" x1="${x}" y1="44" x2="${x}" y2="92"/>`;}for(const [i,n]of notes.entries()){const x=78+n.at*64,y=92-n.step*6;const name=n.rest?'Rest':`${LETTERS[n.step%7]}${Math.floor(n.step/7)+4}${n.acc===1?'♯':n.acc===-1?'♭':''}`;svg+=`<g class="sheet-note${playing&&started.has(i)?' playing':''}" data-index="${i}" tabindex="0" role="button" aria-label="${name}, ${n.beats} beat${n.beats===1?'':'s'}"><title>${name}</title>`;if(n.rest){svg+=`<text class="rest-mark" x="${x}" y="${y+4}">𝄽</text>`;}else{if(n.acc)svg+=`<text class="accidental" x="${x-17}" y="${y+4}">${n.acc===1?'♯':'♭'}</text>`;svg+=`<ellipse class="note-head${n.beats>=2?' open':''}" cx="${x}" cy="${y}" rx="7" ry="4.5" transform="rotate(-18 ${x} ${y})"/>`;if(n.beats<=1){svg+=`<line class="note-stem" x1="${x+6}" y1="${y}" x2="${x+6}" y2="${y-29}"/>`;if(n.beats<1)svg+=`<path class="note-flag" d="M${x+6} ${y-29}q13 7 2 16${n.beats<=.25?` M${x+6} ${y-23}q12 7 2 15`:''}"/>`;}}svg+=`<text class="note-name" x="${x}" y="${y+21}">${name}</text></g>`;}staff.innerHTML=svg;staff.querySelectorAll('.sheet-note').forEach(el=>{const remove=()=>{if(playing)return;notes.splice(Number(el.dataset.index),1);render();};el.addEventListener('click',remove);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();remove();}});});$('#compose-undo').disabled=!notes.length;$('#compose-clear').disabled=!notes.length;}
 function addAt(event){if(playing||event.target.closest('.sheet-note'))return;const rect=staff.getBoundingClientRect(),point=staff.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const local=point.matrixTransform(staff.getScreenCTM().inverse()),step=clamp(Math.round((92-local.y)/6),0,13),at=Math.max(0,Math.round((local.x-78)/64)),occupied=notes.reduce((end,n)=>Math.max(end,n.at+n.beats),0);notes.push({at:Math.max(at,occupied),beats,step,acc:accidental,rest});rest=false;$('#compose-rest').setAttribute('aria-pressed','false');render();$('#compose-status').textContent=`${notes.length} note${notes.length===1?'':'s'} in your melody.`;}
 function stopPlayback(){token++;playing=false;cancelAnimationFrame(frame);for(const id of sounding.values())stop(id);sounding.clear();started.clear();render();$('#compose-play').textContent='Play';$('#compose-stop').disabled=true;$('#compose-staff').classList.remove('composing');}
 function midiFor(n){return NATURAL[n.step%7]+12*Math.floor(n.step/7)+n.acc;}
 function tick(now,run){if(!playing||run!==token)return;const elapsed=(now-began)/1000*bpm/60;for(let i=0;i<notes.length;i++){const n=notes[i],id=`song-compose-${run}-${i}`;if(elapsed>=n.at+n.beats){if(sounding.has(i)){stop(sounding.get(i));sounding.delete(i);}continue;}if(elapsed>=n.at&&!started.has(i)){started.add(i);if(!n.rest){sounding.set(i,id);play(midiFor(n)-(audio.octave+1)*12,id);}}}staff.querySelectorAll('.sheet-note').forEach(el=>el.classList.toggle('playing',started.has(Number(el.dataset.index))&&elapsed<notes[Number(el.dataset.index)].at+notes[Number(el.dataset.index)].beats));if(elapsed>=notes.reduce((end,n)=>Math.max(end,n.at+n.beats),0)){stopPlayback();$('#compose-status').textContent='Melody finished. Edit it or play it again.';return;}frame=requestAnimationFrame(t=>tick(t,run));}
 async function start(){if(!notes.length){$('#compose-status').textContent='Add a few notes to the staff first.';return;}stopPlayback();stopAll();closeListen();const run=++token;try{await ready();}catch(e){$('#compose-status').textContent=e.message;return;}if(run!==token)return;playing=true;began=performance.now();$('#compose-play').textContent='Playing…';$('#compose-stop').disabled=false;staff.classList.add('composing');$('#compose-status').textContent='Your melody is playing on the alto.';frame=requestAnimationFrame(t=>tick(t,run));}
 function close(focus=false){stopPlayback();panel.hidden=true;button.setAttribute('aria-expanded','false');if(focus)button.focus({preventScroll:true});}
 function open(){closeListen();if(!$('#keyboard-panel').hidden)$('#close-keyboard').click();panel.hidden=false;button.setAttribute('aria-expanded','true');$('#compose-name').focus({preventScroll:true});}
 button.addEventListener('click',()=>panel.hidden?open():close());$('#close-compose').addEventListener('click',()=>close(true));staff.addEventListener('click',addAt);$('#compose-play').addEventListener('click',start);$('#compose-stop').addEventListener('click',stopPlayback);
 DURATIONS.forEach(([name,value])=>{const b=document.createElement('button');b.textContent=name;b.dataset.beats=value;b.setAttribute('aria-pressed',String(value===beats));b.addEventListener('click',()=>{beats=value;$('#compose-durations').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(Number(x.dataset.beats)===beats)));});$('#compose-durations').append(b);});$('#compose-accidentals').addEventListener('click',e=>{const b=e.target.closest('[data-acc]');if(!b)return;accidental=Number(b.dataset.acc);$('#compose-accidentals').querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});$('#compose-rest').addEventListener('click',()=>{rest=!rest;$('#compose-rest').setAttribute('aria-pressed',String(rest));$('#compose-status').textContent=rest?'Rest selected. Click the staff to place it.':'Click anywhere on the staff to add a note.';});$('#compose-undo').addEventListener('click',()=>{if(!playing){notes.pop();render();}});$('#compose-clear').addEventListener('click',()=>{stopPlayback();notes=[];render();$('#compose-status').textContent='Click anywhere on the staff to add your first note.';});$('#compose-tempo').addEventListener('input',e=>{bpm=Number(e.target.value);$('#compose-bpm').textContent=`${bpm} BPM`;});$('#keyboard-toggle').addEventListener('click',()=>close());document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!panel.hidden)close(true);});render();return {stop:stopPlayback,close};
}
