import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
import {RoomEnvironment} from './vendor/RoomEnvironment.js';
import {createAlto,addTouches,disposeModel} from './alto-model.js';
export async function createViewer(container,{onPlay,onUnlock,onHover,onError,onView,onInteract,onProgress}){
 const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x090a0b,0);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.8;container.append(renderer.domElement);
 const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.1,80),pmrem=new THREE.PMREMGenerator(renderer),room=new RoomEnvironment();const env=pmrem.fromScene(room,.05);scene.environment=env.texture;scene.environmentIntensity=1.15;room.dispose();pmrem.dispose();
 const keyLight=new THREE.DirectionalLight(0xffe3b3,3);keyLight.position.set(-3,5,5);scene.add(keyLight);const rim=new THREE.DirectionalLight(0xbbd4f4,2);rim.position.set(4,2,-3);scene.add(rim);const fill=new THREE.DirectionalLight(0xffffff,1);fill.position.set(-3,-2,2);scene.add(fill);
 const controls=new OrbitControls(camera,renderer.domElement);controls.autoRotateSpeed=.45;controls.enableDamping=true;controls.dampingFactor=.085;controls.enablePan=false;controls.minDistance=4.5;controls.maxDistance=16;controls.minPolarAngle=.15;controls.maxPolarAngle=Math.PI-.15;controls.rotateSpeed=.7;controls.zoomSpeed=.65;
 let model,current='alto',pointerStart=null,hover=null,dirty=true,frames=0,frame=0,disposed=false;
 const ray=new THREE.Raycaster(),pointer=new THREE.Vector2(),clock=new THREE.Clock(),activeNotes=new Set();
 function reset(){const narrow=container.clientWidth<700;camera.position.set(narrow?4.4:4.8,1.7,narrow?10.2:9.6);controls.target.set(-.05,.12,0);controls.update();dirty=true;}
 function resize(){renderer.setSize(container.clientWidth,container.clientHeight);camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();dirty=true;}
 function select(){current='alto';hover=null;activeNotes.clear();onHover(null);reset();dirty=true;}
 function hit(e){const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const first=ray.intersectObject(model,true)[0];if(!first)return null;let o=first.object;while(o&&o!==model){if(o.userData.note!==undefined)return o.userData.note;o=o.parent;}return null;}
 function pointerDown(e){if(e.button!==0&&e.pointerType!=='touch')return;if(pointerStart){pointerStart.cancelled=true;return;}pointerStart={x:e.clientX,y:e.clientY,id:e.pointerId,n:hit(e),cancelled:false};hover=null;onHover(null);dirty=true;renderer.domElement.classList.add('dragging');onInteract?.();onUnlock();}
 function pointerMove(e){if(pointerStart&&Math.hypot(e.clientX-pointerStart.x,e.clientY-pointerStart.y)>6)pointerStart.cancelled=true;if(e.pointerType==='touch'||pointerStart)return;const n=hit(e);if(hover!==n){hover=n;dirty=true;}renderer.domElement.classList.toggle('over-key',n!==null);onHover(n,e);}
 function pointerUp(e){renderer.domElement.classList.remove('dragging');if(!pointerStart||e.pointerId!==pointerStart.id)return;const p=pointerStart;pointerStart=null;if(!p.cancelled&&p.n!==null&&hit(e)===p.n)onPlay(p.n);}
 function cancel(){pointerStart=null;hover=null;onHover(null);renderer.domElement.classList.remove('dragging','over-key');dirty=true;}
 renderer.domElement.addEventListener('pointerdown',pointerDown);renderer.domElement.addEventListener('pointermove',pointerMove);renderer.domElement.addEventListener('pointerup',pointerUp);renderer.domElement.addEventListener('pointercancel',cancel);renderer.domElement.addEventListener('pointerleave',()=>{hover=null;onHover(null);dirty=true;});window.addEventListener('blur',cancel);
 renderer.domElement.addEventListener('webglcontextlost',e=>{e.preventDefault();onError();});
 controls.addEventListener('change',()=>{dirty=true;});
 container.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','Home'].includes(e.key))return;e.preventDefault();const offset=camera.position.clone().sub(controls.target),s=new THREE.Spherical().setFromVector3(offset);if(e.key==='Home'){reset();return;}if(e.key==='ArrowLeft')s.theta-=.12;if(e.key==='ArrowRight')s.theta+=.12;if(e.key==='ArrowUp')s.phi=Math.max(.2,s.phi-.1);if(e.key==='ArrowDown')s.phi=Math.min(Math.PI-.2,s.phi+.1);if(['+','='].includes(e.key))s.radius=Math.max(4.5,s.radius*.9);if(e.key==='-')s.radius=Math.min(16,s.radius*1.1);camera.position.copy(new THREE.Vector3().setFromSpherical(s).add(controls.target));controls.update();dirty=true;});
 const observer=new ResizeObserver(resize);observer.observe(container);
 function animate(){if(disposed)return;frame=requestAnimationFrame(animate);if(document.hidden)return;controls.update();let moving=false;for(const key of model.userData.keys){const n=key.userData.note,isActive=activeNotes.has(n),target=key.userData.restZ-(isActive?.022:0);const p=key.userData.pearl;p.opacity=isActive?.7:hover===n?.3:0;}if(dirty||moving||frames<4){renderer.render(scene,camera);onView?.();dirty=false;frames++;}}
 model=await createAlto(e=>onProgress?.(e.total?Math.round(e.loaded/e.total*100):0));scene.add(model);select();resize();animate();
 return {select,reset,setRotate(enabled){controls.autoRotate=enabled;dirty=true;},pickPoint(x,y){const r=renderer.domElement.getBoundingClientRect();pointer.set((x-r.left)/r.width*2-1,-(y-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(model,true)[0];return hit?model.worldToLocal(hit.point).toArray():null;},setActive(notes){activeNotes.clear();for(const n of notes)activeNotes.add(n);dirty=true;},get state(){return {instrument:current,camera:camera.position.toArray(),meshes:renderer.info.render.calls,triangles:renderer.info.render.triangles};},keyPositions(){scene.updateMatrixWorld(true);camera.updateMatrixWorld(true);const r=renderer.domElement.getBoundingClientRect();return model.userData.keys.map(k=>{const v=k.userData.dome.getWorldPosition(new THREE.Vector3()).project(camera);const world=k.userData.dome.getWorldPosition(new THREE.Vector3()),visibilityRay=new THREE.Raycaster(camera.position,world.clone().sub(camera.position).normalize()),first=visibilityRay.intersectObject(model,true)[0];let o=first?.object,visible=false;while(o&&o!==model){if(o.userData.note===k.userData.note){visible=true;break;}o=o.parent;}return {note:k.userData.note,x:r.left+(v.x+1)/2*r.width,y:r.top+(1-v.y)/2*r.height,visible:visible&&v.z<1};});},dispose(){disposed=true;cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('blur',cancel);controls.dispose();disposeModel(model);env.dispose();renderer.dispose();}};
}
